run_config_search_disable: True

profile_models:
  xgb_model:
    parameters:
      concurrency: [1, 2, 4, 8, 16, 32, 64]
      batch_sizes: [1, 16, 128, 1024]
    model_config_parameters:
      max_batch_size: [1024768]
      instance_group:
        - kind: KIND_CPU
          count: [1]
